### ISSUE TITLE
Another Possible Error

### ISSUE THREAD

**Issue by fxfactorial** [BelBES/thinkpad_x1_carbon_6th_linux#2]
You are from the Lord, thank you!

So just ran this, works but did run into hunk #7 giving error because 

```
   \_SB.SGOV (DerefOf (Arg0 [0x02]), (DerefOf (Arg0 [0x03]) ^ 0x01))
```

is already being xored, or at least was in mine. Good to know and possibly provide another version of patch so that easier for folks to use?

**Comment by bes-dev** [comment]
So, it's works fine for me. But if you have any errors in patching process, you can fix it by hand. No hesitate to delete some strings from patch.

**Comment by fxfactorial** [comment]
I know that, I’m documenting this so that other people have a bread crumb
